network:
    ip_address: 192.168.4.14
    hostname: vagrant.localhost
    aliases:
        - www.vagrant.localhost
#synced_folders:
#    - { host: ~/Sites/, guest: /Sites, owner: www-data, group: www-data, mount_options: ["dmode=777","fmode=666"]}

