network:
    ip_address: 192.168.4.14
    hostname: vagrant.localhost
    aliases:
        - www.vagrant.localhost
#synced_folders:
#    - { host: htdocs, guest: /var/www/html, owner: www-data, group: www-data }
